EXERCISES = {
    # ================== PUSH ===============================
    "close_grip_bench": {"name": "Barbell Close-Grip Bench", "role": "auxiliary", "ask_input": True},
    "dips": {"name": "Dips", "role": "auxiliary", "ask_input": True},
    "flat_bench": {"name": "Barbell Flat Bench", "role": "main", "ask_input": True},
    "incline_bench": {"name": "Barbell Incline Bench", "role": "main", "ask_input": True},
    "lateral_raises": {"name": "Delt Raises", "role": "isolation", "ask_input": True},
    "machine_chest_press": {"name": "Machine Chest Press", "role": "auxiliary", "ask_input": True},
    "shoulder_press": {"name": "Shoulder Press", "role": "main", "ask_input": True},
    "skull_crushers": {"name": "Skull Crushers", "role": "isolation", "ask_input": True},
    "tricep_pushdowns": {"name": "Cable Tricep Pushdowns", "role": "isolation", "ask_input": True},

    # ================== PULL ===============================
    "barbell_back_row": {"name": "Bent Over Row", "role": "main", "ask_input": True},
    "barbell_curl": {"name": "Barbell Curl", "role": "isolation", "ask_input": True},
    "machine_row": {"name": "Machine Row", "role": "auxiliary", "ask_input": True},
    "seated_cable_row": {"name": "Seated Cable Row", "role": "auxiliary", "ask_input": True},
    "pull_down": {"name": "Lat Pulldown", "role": "main", "ask_input": True},
    "pull_ups": {"name": "Pull Ups", "role": "main", "ask_input": True},
    "pullovers": {"name": "Lat Pullovers", "role": "isolation", "ask_input": True},
    "rear_delts": {"name": "Rear Delt Fly", "role": "isolation", "ask_input": True},
    "incline_bench_support_back_row": {"name": "Chest Supported Row", "role": "auxiliary", "ask_input": True},

    # ================== LEGS ===============================
    "back_squat": {"name": "Back Squat", "role": "main", "ask_input": True},
    "calf_raises": {"name": "Calf Raises", "role": "isolation", "ask_input": True},
    "cable_pull_through": {"name": "Cable Pull Through", "role": "auxiliary", "ask_input": True},
    "deadlift": {"name": "Conventional Deadlift", "role": "main", "ask_input": True},
    "front_squat": {"name": "Front Squat", "role": "main", "ask_input": True},
    "goblet_squat": {"name": "Goblet Squat", "role": "auxiliary", "ask_input": True},
    "hip_thrust": {"name": "Hip Thrust", "role": "main", "ask_input": True},
    "leg_curl": {"name": "Leg Curl", "role": "isolation", "ask_input": True},
    "leg_extension": {"name": "Leg Extension", "role": "isolation", "ask_input": True},
    "leg_press": {"name": "Leg Press", "role": "main", "ask_input": True},
    "rdl": {"name": "Barbell RDL", "role": "main", "ask_input": True},
    "reverse_lunge": {"name": "Reverse Lunge", "role": "auxiliary", "ask_input": True},
    "seated_leg_curl": {"name": "Seated Leg Curl", "role": "isolation", "ask_input": True},
    "split_squat": {"name": "Bulgarian Split Squat", "role": "auxiliary", "ask_input": True},
    "step_up": {"name": "Step Up", "role": "auxiliary", "ask_input": True},
}